name: ESLint_Prettier

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linters:
    name: Run eslint and prettier scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint
          npm i eslint-config-prettier

      - name: Run linters
        run: npm run linters
